name: Fly
main: Nerahikada\Fly\Main
version: 2.0.0
api: [3.0.0, 4.0.0]
load: POSTWORLD
author: ねらひかだ
description: 飛べます！
website: https://github.com/Nerahikada/Fly

commands:
  fly:
    description: 飛行を切り替えます
    usage: /fly